'use client';
import { useEffect,useState } from 'react';
import { BroadcastComposer } from './BroadcastComposer';
import { TemplateLibrary } from './TemplateLibrary';
type Campaign={id:string;body:string;provider_sender:string;recipient_count:number;created_at:string;counts:Record<string,number>};
type Delivery={id:string;phone:string;state:string;attempts:number;report_attempts:number;provider_campaign_id:string|null;last_error:string|null};
export function CommunicationsWorkspace(){
 const [campaigns,setCampaigns]=useState<Campaign[]>([]),[cursor,setCursor]=useState<string|null>(null),[version,setVersion]=useState(0),[enabled,setEnabled]=useState(false),[selection,setSelection]=useState(''),[deliveries,setDeliveries]=useState<Delivery[]>([]),[deliveryCursor,setDeliveryCursor]=useState<string|null>(null),[loaded,setLoaded]=useState('');
 const [template,setTemplate]=useState({body:'',version:0}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const abort=new AbortController();fetch('/api/communications',{cache:'no-store',signal:abort.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);if(!abort.signal.aborted){setCampaigns(data.items);setCursor(data.next_cursor);setEnabled(data.sms_enabled);}}).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[version]);
 useEffect(()=>{if(!selection)return;const abort=new AbortController();fetch('/api/communications?'+new URLSearchParams({view:'deliveries',broadcast_id:selection}),{cache:'no-store',signal:abort.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);if(!abort.signal.aborted){setDeliveries(data.items);setDeliveryCursor(data.next_cursor);setLoaded(selection);}}).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[selection,version]);
 async function more(recipients=false){setBusy(true);setError('');try{const query=recipients?new URLSearchParams({view:'deliveries',broadcast_id:selection,after:deliveryCursor!}):new URLSearchParams({after:cursor!});const response=await fetch('/api/communications?'+query,{cache:'no-store'}),data=await response.json();if(!response.ok)throw new Error(data.error);if(recipients){setDeliveries(previous=>[...previous,...data.items]);setDeliveryCursor(data.next_cursor);}else{setCampaigns(previous=>[...previous,...data.items]);setCursor(data.next_cursor);}}catch(e){setError(e instanceof Error?e.message:'Report unavailable.');}finally{setBusy(false);}}
 async function retry(event:React.FormEvent<HTMLFormElement>,delivery:Delivery){event.preventDefault();setBusy(true);setError('');const data=new FormData(event.currentTarget);try{const response=await fetch('/api/communications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:delivery.state==='failed'?'retry':'reconcile',id:delivery.id,reason:data.get('reason'),provider_campaign_id:data.get('provider_campaign_id')||undefined})}),result=await response.json();if(!response.ok)throw new Error(result.error);setVersion(v=>v+1);}catch(e){setError(e instanceof Error?e.message:'Retry unavailable.');}finally{setBusy(false);}}
 return <div className="space-y-6 pb-8"><header><h1 className="text-3xl font-semibold">Church communications</h1><p className="text-sm text-slate-600 mt-2">Consent-based broadcasts and real delivery reports</p></header>{error&&<p role="alert" className="rounded-xl bg-rose-50 text-rose-800 p-4">{error}</p>}<div className="grid gap-6 lg:grid-cols-3"><div className="lg:col-span-2"><BroadcastComposer key={template.version} initialMessage={template.body} smsEnabled={enabled} onQueued={()=>setVersion(v=>v+1)}/></div><TemplateLibrary onSelectTemplate={body=>setTemplate(previous=>({body,version:previous.version+1}))}/></div>
 <section className="rounded-2xl border bg-white p-5 space-y-4"><div className="flex flex-wrap justify-between gap-3"><h2 className="font-semibold text-lg">Broadcast history</h2><button className="text-church-700 underline" disabled={busy} onClick={()=>{setError('');setVersion(v=>v+1);}}>Refresh reports</button></div><p className="text-sm text-slate-600">Accepted means mNotify accepted the request. Delivered requires a matching provider delivery report. An uncertain send is held for reconciliation and is never automatically resent.</p>{!campaigns.length&&<p>No saved broadcasts.</p>}{campaigns.map(c=><article key={c.id} className="border rounded-xl p-4 space-y-2"><p className="text-xs text-slate-500">{new Date(c.created_at).toLocaleString('en-GB',{timeZone:'Africa/Accra'})} · {c.provider_sender} · {c.recipient_count} recipients</p><p className="whitespace-pre-wrap">{c.body}</p><div className="flex flex-wrap gap-3 text-sm">{Object.entries(c.counts).map(([state,count])=><span key={state}>{state}: {count}</span>)}</div><button className="text-church-700 underline" disabled={busy} onClick={()=>setSelection(c.id)}>View recipients and failures</button></article>)}{cursor&&<button className="underline" disabled={busy} onClick={()=>void more()}>Load more broadcasts</button>}</section>
 {selection&&<section className="rounded-2xl border bg-white p-5 space-y-4"><h2 className="font-semibold text-lg">Recipient delivery report</h2>{loaded!==selection?<p role="status">Loading recipients…</p>:deliveries.map(d=><article key={d.id} className="border rounded-xl p-4 space-y-2"><p className="font-semibold">{d.phone} · {d.state}</p><p className="text-sm">Send attempts: {d.attempts}/3 · Report checks: {d.report_attempts}/12</p>{d.provider_campaign_id&&<p className="text-xs break-all">Provider reference: {d.provider_campaign_id}</p>}{d.last_error&&<p className="text-sm text-amber-800">{d.last_error}</p>}{d.report_attempts>=12&&d.state==='accepted'&&<p className="text-sm">No final report yet. Check provider history and request another report.</p>}
 {(d.state==='failed'&&d.attempts<3||d.state==='accepted'||d.state==='uncertain')&&<form onSubmit={e=>void retry(e,d)} className="space-y-2">{d.state==='uncertain'&&!d.provider_campaign_id&&<label className="block">Campaign reference from mNotify history<input name="provider_campaign_id" required maxLength={128} className="block w-full border rounded-lg p-2" disabled={busy}/></label>}<label className="block">Reason<input name="reason" required maxLength={300} className="block w-full border rounded-lg p-2" disabled={busy}/></label><button className="text-church-700 underline" disabled={busy}>{d.state==='failed'?'Retry confirmed failure (may incur another SMS charge)':'Reconcile delivery report (does not resend)'}</button></form>}</article>)}{loaded===selection&&deliveryCursor&&<button className="underline" disabled={busy} onClick={()=>void more(true)}>Load more recipients</button>}</section>}
 </div>;
}
