'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import { AttendanceOverview } from './AttendanceOverview';
import { DeviceManagement } from './DeviceManagement';
type Service={id:string;name:string;starts_at:string;ends_at:string;completed_at:string|null};
type Member={id:string;first_name:string;last_name:string;present:boolean|null;excused:boolean|null;household_id:string|null};
type Household={id:string;name:string;member_id:string|null};
export function AttendanceWorkspace(){
 const [services,setServices]=useState<Service[]>([]),[members,setMembers]=useState<Member[]>([]),[households,setHouseholds]=useState<Household[]>([]),[service,setService]=useState(''),[household,setHousehold]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[pending,setPending]=useState(false);
 const operations=useRef(new Map<string,string>());
 const sequence=useRef({value:0});
 const [revision,setRevision]=useState(0);
 const load=useCallback(async()=>{const request=++sequence.current.value;const results=await Promise.all(['services','households',...(service?['roster']:[])].map(async view=>{const r=await fetch(`/api/attendance?view=${view}&service_id=${service}`,{cache:'no-store'});if(!r.ok)throw Error('Attendance could not be loaded.');return {view,data:await r.json()};}));if(request!==sequence.current.value)return;for(const {view,data} of results){if(view==='services')setServices(data.items);if(view==='households')setHouseholds(data.items);if(view==='roster')setMembers(data.items);}},[service]);
 useEffect(()=>{const tracker=sequence.current;let active=true;queueMicrotask(()=>{if(active)void load().catch(e=>setError(e.message));});return()=>{active=false;tracker.value++;};},[load]);
 async function save(body:Record<string,unknown>){setPending(true);setError('');setMessage('');try{const r=await fetch('/api/attendance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await r.json();if(!r.ok)throw Error(data.error);setMessage(`Saved to the database. Record: ${data.id}`);try{await load();}catch{setError('The write was saved; refreshing the list failed. Retry load.');}setRevision(value=>value+1);return true;}catch(e){setError(e instanceof Error?e.message:'Save failed. Form entries retained.');return false;}finally{setPending(false);}}
 async function formSave(e:React.FormEvent<HTMLFormElement>,action:string){e.preventDefault();const form=e.currentTarget,body:Record<string,unknown>=Object.fromEntries(new FormData(form));body.action=action;if(action==='service'){body.attendance_eligible=body.attendance_eligible==='on';body.starts_at=new Date(String(body.starts_at)).toISOString();body.ends_at=new Date(String(body.ends_at)).toISOString();}if(action==='eligibility'){body.expected_from=new Date(String(body.expected_from)).toISOString();if(body.expected_until)body.expected_until=new Date(String(body.expected_until)).toISOString();}if(await save(body))form.reset();}
 const selected=services.find(s=>s.id===service);
 return <div className="max-w-5xl mx-auto space-y-6"><h1 className="text-2xl font-semibold">Services and attendance</h1>{error&&<p role="alert">{error} <button onClick={()=>void load().then(()=>setError('')).catch(e=>setError(e.message))} className="underline">Retry load</button></p>}<p role="status">{message}</p>
  <form onSubmit={e=>void formSave(e,'service')} className="bg-white p-5 border rounded space-y-3"><h2 className="font-semibold">Create dated service</h2><label className="block">Name<input required name="name" maxLength={160} className="border p-2 ml-2"/></label><label className="block">Type<select name="event_type" className="border p-2 ml-2"><option value="service">Service</option><option value="cell">Cell meeting</option><option value="vigil">Vigil</option></select></label><label className="block">Cell group (required for cell meeting)<input name="cell_group" maxLength={100} className="border p-2 ml-2"/></label>{['starts_at','ends_at'].map(name=><label className="block" key={name}>{name==='starts_at'?'Starts':'Ends'} (your local timezone)<input required type="datetime-local" name={name} className="border p-2 ml-2"/></label>)}<label className="block"><input type="checkbox" name="attendance_eligible" defaultChecked/> Counts towards expected attendance</label><button disabled={pending} className="underline">Create service</button></form>
  <label className="block">Service<select value={service} onChange={e=>{setMembers([]);setService(e.target.value);}} className="border p-2 ml-2"><option value="">Choose service</option>{services.map(s=><option key={s.id} value={s.id}>{s.name} · {new Date(s.starts_at).toLocaleString()} {s.completed_at?'(completed)':''}</option>)}</select></label>
  <label className="block">Household filter<select value={household} onChange={e=>setHousehold(e.target.value)} className="border p-2 ml-2"><option value="">All members</option>{Array.from(new Map(households.map(h=>[h.id,h])).values()).map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></label><p>Confirm each member separately. Household membership comes from saved records.</p>
  {selected&&members.filter(m=>!household||m.household_id===household).map(m=><form key={m.id} onSubmit={async e=>{e.preventDefault();const f=e.currentTarget,data=new FormData(f);const body={action:'record',service_id:service,member_id:m.id,state:String(data.get('state')),reason:String(data.get('reason')),recorded_at:new Date(String(data.get('recorded_at'))).toISOString()};const key=JSON.stringify(body);let operation=operations.current.get(key);if(!operation){operation=crypto.randomUUID();operations.current.set(key,operation);}if(await save({...body,operation_id:operation}))operations.current.delete(key);}} className="border p-3 rounded bg-white space-y-2"><h3>{m.first_name} {m.last_name} · {m.present?'Present':m.excused?'Excused':'No present record'}</h3><p className="text-xs">Member ID: {m.id}</p><label>State<select name="state" className="border p-2 ml-2"><option value="present">Present</option><option value="excused">Excused</option><option value="absent">Absent</option></select></label><label className="block">Recorded service time (local)<input required type="datetime-local" name="recorded_at" className="border p-2 ml-2"/></label><label className="block">Reason<input required name="reason" maxLength={300} className="border p-2 ml-2"/></label><label className="block"><input required type="checkbox"/> I confirm this member and attendance state</label><button disabled={pending} className="underline">Save attendance / correction</button></form>)}
  <details className="border p-4"><summary>Household management and future eligibility</summary><p>Eligibility intervals affect future service completion snapshots. Transfers/end of participation should set an end date. Existing snapshots remain historical.</p>{[{action:'household',fields:['name']},{action:'household_member',fields:['member_id','household_id']},{action:'eligibility',fields:['member_id','expected_from','expected_until','participation_status']}].map(spec=><form key={spec.action} onSubmit={e=>void formSave(e,spec.action)} className="p-3 space-y-2"><h3>{spec.action.replaceAll('_',' ')}</h3>{spec.fields.map(name=><label className="block" key={name}>{name.replaceAll('_',' ')}<input required={!['household_id','expected_until','participation_status'].includes(name)} type={name.startsWith('expected_')?'datetime-local':'text'} name={name} className="border p-2 ml-2"/></label>)}<button disabled={pending} className="underline">Save</button></form>)}</details>
  <DeviceManagement/>
  <AttendanceOverview key={revision}/>
 </div>;
}
