'use client';
import { useEffect,useState } from 'react';
import { CheckInCode } from '../kiosk/CheckInCode';
type Service={id:string;name:string;starts_at:string;ends_at:string;completed_at:string|null};
export function MemberAttendance(){
 const [services,setServices]=useState<Service[]>([]),[history,setHistory]=useState<{id:string;name:string;starts_at:string;present:boolean;excused:boolean}[]>([]),[issued,setIssued]=useState<{token:string;service:string}|null>(null),[message,setMessage]=useState(''),[pending,setPending]=useState(false);
 useEffect(()=>{const c=new AbortController();Promise.all(['services','personal'].map(async view=>{const r=await fetch(`/api/attendance?view=${view}`,{cache:'no-store',signal:c.signal});if(!r.ok)throw Error();const data=await r.json();if(view==='services')setServices(data.items);else setHistory(data.items);})).catch(()=>{if(!c.signal.aborted)setMessage('Attendance could not be loaded. Refresh to retry.');});return()=>c.abort();},[]);
 useEffect(()=>{if(!issued)return;const timer=window.setTimeout(()=>{setIssued(null);setMessage('Check-in code expired. Request a new code if the service is still open.');},300000);return()=>window.clearTimeout(timer);},[issued]);
 async function issue(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setPending(true);setIssued(null);try{const service=String(new FormData(e.currentTarget).get('service_id'));const r=await fetch('/api/kiosk/qr',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({service_id:service})});const data=await r.json();if(!r.ok)throw Error(data.error);setIssued({token:data.token,service:data.service_id});setMessage(`Service ID: ${data.service_id}. Present this code at the attended kiosk within five minutes.`);}catch(e){setMessage(e instanceof Error?e.message:'Token unavailable.');}finally{setPending(false);}}
 return <section className="p-5 border rounded-xl bg-white space-y-3"><h2 className="font-bold">My attendance</h2><p>Check-in opens one hour before the service and closes at its end.</p><form onSubmit={issue}><label>Service<select required name="service_id" className="border p-2 ml-2">{services.filter(s=>!s.completed_at).map(s=><option key={s.id} value={s.id}>{s.name} · {new Date(s.starts_at).toLocaleString()}</option>)}</select></label><button disabled={pending} className="underline ml-3">Get check-in code</button></form><p role="status">{message}</p>{issued&&<><CheckInCode token={issued.token} service={issued.service}/><code className="block break-all select-all">{issued.token}</code></>}{!history.length?<p>No attendance records yet.</p>:history.map(a=><p key={a.id}>{a.name} · {new Date(a.starts_at).toLocaleDateString()} · {a.present?'Present':a.excused?'Excused':'Absent'}</p>)}</section>;
}
