'use client';
import { useEffect,useState } from 'react';
type Member={id:string;first_name:string;last_name:string;phone:string|null};
export function FinanceMemberPicker({name,value,onChange,emptyLabel='Anonymous'}:{name?:string;value?:string;onChange?:(value:string)=>void;emptyLabel?:string}){
 const [search,setSearch]=useState(''),[archived,setArchived]=useState(false),[items,setItems]=useState<Member[]>([]),[selection,setSelection]=useState<Member|null>(null),[error,setError]=useState('');
 useEffect(()=>{const abort=new AbortController();fetch('/api/core/members?'+new URLSearchParams({limit:'100',search,archived:String(archived)}),{cache:'no-store',signal:abort.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);if(!abort.signal.aborted){setItems(data.items);setError('');}}).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[search,archived]);
 const selected=value??selection?.id??'',options=selection&&!items.some(m=>m.id===selection.id)?[selection,...items]:items;
 return <div className="space-y-2"><label className="block">Find donor<input className="block w-full border rounded-lg p-2" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name" maxLength={100}/></label><label className="block text-sm"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/> Search archived members</label><label className="block">Donor<select className="block w-full border rounded-lg p-2" name={name} value={selected} onChange={e=>{setSelection(options.find(m=>m.id===e.target.value)||null);onChange?.(e.target.value);}}><option value="">{emptyLabel}</option>{options.map(m=><option key={m.id} value={m.id}>{m.first_name} {m.last_name} · {m.phone||m.id.slice(0,8)}</option>)}</select></label><p className="text-xs text-slate-500">Up to 100 matches. Narrow the search to find the correct donor.</p>{error&&<p role="alert">{error}</p>}</div>;
}
