'use client';
import { useEffect,useRef,useState } from 'react';
import { PdfStatementGenerator } from './PdfStatementGenerator';
import { FinanceMemberPicker } from './FinanceMemberPicker';
import { RefundEvidencePicker } from './RefundEvidencePicker';
type Entry={id:string;donor:string;kind:string;amount_minor:string;currency:string;fund:string;method:string;reference:string;given_at:string};
type Report={items:Entry[];totals:{currency:string;fund:string;net_minor:string}[];monthly:{month:string;currency:string;net_minor:string}[];attempts:{reference:string;amount_minor:string;status:string}[];next_cursor:string|null;next_attempt_cursor:string|null};
const money=(value:string)=>{const n=BigInt(value),a=n<0n?-n:n;return `${n<0n?'-':''}${a/100n}.${String(a%100n).padStart(2,'0')}`;};
const field='block rounded-lg border border-slate-300 bg-white p-2 w-full';
const button='rounded-lg bg-church-700 px-4 py-2 text-white disabled:opacity-50';
async function post(url:string,body:object){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Operation failed.');return result;}
export function FinanceWorkspace({own=false}:{own?:boolean}){
 const [year,setYear]=useState(String(new Date().getFullYear())),[currency,setCurrency]=useState('GHS'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[member,setMember]=useState('');
 const [storedReport,setReport]=useState<Report|null>(null),[loaded,setLoaded]=useState(''),[error,setError]=useState(''),[readError,setReadError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[version,setVersion]=useState(0),[enabled,setEnabled]=useState(false);
 const [operation,setOperation]=useState(()=>crypto.randomUUID()),[reverse,setReverse]=useState<Entry|null>(null);
 const query=new URLSearchParams({year,currency,...(own?{scope:'own'}:{}),...(from?{from}:{}),...(to?{to}:{}),...(!own&&member?{member_id:member}:{})}).toString();
 const report=loaded===query+version?storedReport:null;
 const currentQuery=useRef(query+version);useEffect(()=>{currentQuery.current=query+version;},[query,version]);
 useEffect(()=>{let active=true;fetch('/api/payments/configuration').then(r=>r.json()).then(data=>{if(active)setEnabled(data.enabled===true);}).catch(()=>{});return()=>{active=false;};},[]);
 useEffect(()=>{const abort=new AbortController();fetch('/api/finance?'+query,{signal:abort.signal,cache:'no-store'}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);if(!abort.signal.aborted){setReport(data);setLoaded(query+version);setReadError('');}}).catch(e=>{if(!abort.signal.aborted)setReadError(e.message);});return()=>abort.abort();},[query,version]);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');setNotice('');const form=event.currentTarget,data=new FormData(form);
  try{const values=Object.fromEntries(data.entries());if(own){const result=await post('/api/payments/checkout',{operation_id:operation,amount:values.amount,fund:values.fund,anonymous:data.get('anonymous')==='on'});if(result.checkout_url)window.location.assign(result.checkout_url);else setNotice('Payment status: '+result.status);}
   else{await post('/api/finance',{...values,action:reverse?(reverse.method==='hubtel'?'refund':'reverse'):'manual',operation_id:operation,...(reverse?{id:reverse.id}:{given_at:values.given_at+'T00:00:00+00:00'})});setNotice('Contribution saved.');setReverse(null);form.reset();setVersion(v=>v+1);setOperation(crypto.randomUUID());}
  }catch(e){setError(e instanceof Error?e.message:'Submission failed.');if(own)setVersion(v=>v+1);}finally{setBusy(false);}
 }
 async function verify(reference:string){setBusy(true);setError('');try{const result=await post('/api/payments/verify',{reference});setNotice('Verified status: '+result.status);setVersion(v=>v+1);}catch(e){setError(e instanceof Error?e.message:'Verification unavailable.');}finally{setBusy(false);}}
 async function more(){if(!report?.next_cursor)return;setBusy(true);const generation=query+version;try{const response=await fetch('/api/finance?'+query+'&after='+report.next_cursor,{cache:'no-store'}),data=await response.json();if(!response.ok)throw new Error(data.error);if(currentQuery.current===generation)setReport(previous=>previous?{...previous,items:[...previous.items,...data.items],next_cursor:data.next_cursor}:data);}catch(e){setError(e instanceof Error?e.message:'Could not load records.');}finally{setBusy(false);}}
 async function moreAttempts(){if(!report?.next_attempt_cursor)return;setBusy(true);const generation=query+version;try{const response=await fetch('/api/finance?'+query+'&view=attempts&attempt_after='+report.next_attempt_cursor,{cache:'no-store'}),data=await response.json();if(!response.ok)throw new Error(data.error);if(currentQuery.current===generation)setReport(previous=>previous?{...previous,attempts:[...previous.attempts,...data.attempts],next_attempt_cursor:data.next_attempt_cursor}:previous);}catch(e){setError(e instanceof Error?e.message:'Could not load attempts.');}finally{setBusy(false);}}
 return <div className="space-y-6 pb-8">
  <header><h1 className="text-3xl font-semibold text-slate-900">{own?'My giving':'Financial ledger'}</h1><p className="mt-2 text-sm text-slate-600">Recorded giving, receipts and statements · Africa/Accra</p></header>
  {(error||readError)&&<p role="alert" className="rounded-xl bg-rose-50 p-4 text-rose-800">{error||readError}</p>}{notice&&<p role="status" className="rounded-xl bg-emerald-50 p-4 text-emerald-800">{notice}</p>}
  <section className="rounded-2xl border border-slate-200 bg-white p-5 space-y-4"><h2 className="font-semibold">Report filters</h2><div className="grid gap-3 sm:grid-cols-4">
   <label>Year<input className={field} type="number" min="2000" max="2100" value={year} onChange={e=>setYear(e.target.value)}/></label><label>Currency<select className={field} value={currency} onChange={e=>setCurrency(e.target.value)}><option>GHS</option><option>USD</option></select></label>
   <label>From<input className={field} type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input className={field} type="date" value={to} onChange={e=>setTo(e.target.value)}/></label>
   {!own&&<div className="sm:col-span-4"><FinanceMemberPicker value={member} onChange={setMember} emptyLabel="All donors"/></div>}
  </div><PdfStatementGenerator query={query}/></section>
  {!report&&!error&&<p role="status">Loading giving records…</p>}
  {report&&<><section className="grid gap-3 sm:grid-cols-3">{report.totals.map(t=><div key={t.currency+t.fund} className="rounded-2xl border bg-white p-4"><p className="text-sm text-slate-600">{t.fund} · net</p><p className="text-xl font-semibold">{t.currency} {money(t.net_minor)}</p></div>)}{!report.totals.length&&<p>No recorded giving for this selection.</p>}</section>
   <section role="region" aria-label="Giving records table" tabIndex={0} className="rounded-2xl border bg-white p-5 overflow-x-auto"><h2 className="font-semibold mb-3">Giving records</h2><table className="w-full text-sm text-left"><thead><tr>{['Date','Donor / fund','Amount','Reference','Actions'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{report.items.map(e=><tr key={e.id} className="border-t"><td className="p-2 whitespace-nowrap">{new Date(e.given_at).toLocaleDateString('en-GB',{timeZone:'Africa/Accra'})}</td><td className="p-2">{e.donor}<br/>{e.fund} · {e.kind} · {e.method}</td><td className="p-2 whitespace-nowrap">{e.currency} {money(e.amount_minor)}</td><td className="p-2 break-all">{e.reference}</td><td className="p-2 space-y-2"><a className="block text-church-700 underline" href={'/api/finance?'+query+'&format=pdf&receipt='+e.id}>Receipt / entry</a>{!own&&e.kind==='credit'&&<button className="text-rose-700 underline" disabled={busy} onClick={()=>{setReverse(e);setOperation(crypto.randomUUID());}}>{e.method==='hubtel'?'Record confirmed refund':'Reverse'}</button>}</td></tr>)}</tbody></table>{report.next_cursor&&<button className={button+' mt-4'} disabled={busy} onClick={more}>Load more</button>}</section>
   {!own&&report.monthly.length>0&&<section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">Monthly net giving</h2>{report.monthly.map(m=><p key={m.month+m.currency}>{m.month} · {m.currency} {money(m.net_minor)}</p>)}</section>}
   <section className="rounded-2xl border bg-white p-5 space-y-3"><h2 className="font-semibold">Payment attempts</h2><p className="text-sm text-slate-600">Pending or failed attempts are excluded from totals. Anonymous giving has no member statement link.</p>{report.attempts.map(a=><div key={a.reference} className="flex flex-wrap gap-3 border-t pt-3"><span className="break-all">{a.reference} · GHS {money(a.amount_minor)} · {a.status}</span><button className="text-church-700 underline" disabled={busy||!enabled} onClick={()=>verify(a.reference)}>Check with Hubtel</button></div>)}{!report.attempts.length&&<p>No payment attempts for this selection.</p>}{report.next_attempt_cursor&&<button className={button} disabled={busy} onClick={moreAttempts}>Load more payment attempts</button>}</section>
  </>}
  <section className="rounded-2xl border bg-white p-5 space-y-4"><h2 className="font-semibold">{own?'Give online':reverse?(reverse.method==='hubtel'?'Record a confirmed Hubtel refund':'Reverse a contribution'):'Record cash or bank giving'}</h2>
   {own&&!enabled?<p>Online giving is awaiting church payment configuration. Please contact the church office for giving arrangements.</p>:<form onSubmit={submit} className="grid gap-3 sm:grid-cols-2">
    {reverse&&<p className="sm:col-span-2 break-all">Original reference: {reverse.reference}. Reversals preserve the original record.</p>}
    <label>Amount {own?'(GHS)':''}<input name="amount" className={field} inputMode="decimal" required pattern="[0-9]+(\.[0-9]{1,2})?" disabled={busy}/></label>
    {!reverse&&<><label>Fund<select name="fund" className={field} defaultValue="offering" disabled={busy}>{['tithe','offering','building_fund','missions','special_seed','other'].map(f=><option key={f} value={f}>{f.replaceAll('_',' ')}</option>)}</select></label>{own?<label><input name="anonymous" type="checkbox" disabled={busy}/> Give anonymously (excluded from my statement)</label>:<><label>Currency<select name="currency" className={field} disabled={busy}><option>GHS</option><option>USD</option></select></label><label>Method<select name="method" className={field} disabled={busy}><option value="cash">Cash</option><option value="bank">Bank</option></select></label><FinanceMemberPicker name="member_id"/><label>Reference<input name="reference" className={field} required maxLength={160} disabled={busy}/></label><label>Giving date (Africa/Accra)<input name="given_at" className={field} type="date" required max={new Date().toISOString().slice(0,10)} disabled={busy}/></label></>}</>}
    {reverse?.method==='hubtel'&&<><p className="sm:col-span-2">Record only a refund already completed in the Hubtel portal. Upload its evidence in Documents first.</p><label>Hubtel refund reference<input name="reference" className={field} required maxLength={160} disabled={busy}/></label><RefundEvidencePicker/></>}{!own&&<label>Reason / recording note<input name="reason" className={field} required maxLength={300} disabled={busy}/></label>}
    <div className="sm:col-span-2 flex gap-3"><button className={button} disabled={busy||!operation}>{busy?'Saving…':own?'Continue to Hubtel':reverse?(reverse.method==='hubtel'?'Record confirmed refund':'Record reversal'):'Record contribution'}</button>{reverse&&<button type="button" onClick={()=>{setReverse(null);setOperation(crypto.randomUUID());}}>Cancel reversal</button>}</div>
   </form>}
  </section>
 </div>;
}
