'use client';
import {useEffect,useRef,useState} from 'react';
import {FileUpload} from './FileUpload';
type Document={id:string;title:string;revision:number;can_edit:boolean};
type Version={id:string;version:number;original_name:string;media_type:string;byte_size:string;created_at:string};
export function DocumentsWorkspace(){
 const [items,setItems]=useState<Document[]>([]),[cursor,setCursor]=useState<string|null>(null),[selected,setSelected]=useState<string|null>(null),[document,setDocument]=useState<Document|null>(null),[versions,setVersions]=useState<Version[]>([]),[fileId,setFileId]=useState(''),[refresh,setRefresh]=useState(0),[notice,setNotice]=useState(''),[title,setTitle]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState('');
 const [nextVersion,setNextVersion]=useState<number|null>(null);
 const olderRequest=useRef<AbortController|null>(null);
 useEffect(()=>()=>{olderRequest.current?.abort();},[selected,refresh]);
 useEffect(()=>{const controller=new AbortController();fetch('/api/documents',{signal:controller.signal}).then(async response=>{if(!response.ok)throw Error('Documents unavailable.');const data=await response.json();setItems(data.items);setCursor(data.next_cursor);}).catch(error=>{if(error.name!=='AbortError')setNotice(error.message);});return()=>controller.abort();},[refresh]);
 useEffect(()=>{if(!selected)return;const controller=new AbortController();fetch('/api/documents?id='+selected,{signal:controller.signal}).then(async response=>{if(!response.ok)throw Error('Document unavailable.');const data=await response.json();setDocument(data.document);setTitle(data.document.title);setVersions(data.versions);setNextVersion(data.next_version);setFileId(data.versions[0]?.id||'');}).catch(error=>{if(error.name!=='AbortError')setNotice(error.message);});return()=>controller.abort();},[selected,refresh]);
 const version=versions.find(v=>v.id===fileId),url=selected&&fileId?`/api/documents/${selected}?version=${fileId}`:'';
 useEffect(()=>{if(!url||version?.media_type!=='text/plain')return;const controller=new AbortController();fetch(url,{signal:controller.signal}).then(async response=>{if(!response.ok)throw Error('Preview unavailable.');const value=await response.text();setPreview(value.slice(0,10000)+(value.length>10000?'\n[Preview truncated; download the original file.]':''));}).catch(error=>{if(error.name!=='AbortError')setPreview('Preview unavailable. Download the original file.');});return()=>controller.abort();},[url,version?.media_type]);
 async function mutate(action:'rename'|'archive'){if(!document)return;setBusy(true);setNotice('');try{const response=await fetch('/api/documents',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id:document.id,revision:document.revision,...(action==='rename'?{title}:{})})});const data=await response.json();if(!response.ok)throw Error(data.error);setNotice(action==='archive'?'Document deleted from the vault. Files are retained for 30 days before cleanup.':'Title saved.');if(action==='archive'){setSelected(null);setDocument(null);}setRefresh(n=>n+1);}catch(error){setNotice((error as Error).message);}finally{setBusy(false);}}
 async function more(){setBusy(true);try{const response=await fetch('/api/documents?after='+cursor);if(!response.ok)throw Error('Documents unavailable.');const data=await response.json();setItems(old=>[...old,...data.items]);setCursor(data.next_cursor);}catch(error){setNotice((error as Error).message);}finally{setBusy(false);}}
 function uploaded(id:string){setSelected(id);setRefresh(n=>n+1);}
 async function older(){setBusy(true);const controller=new AbortController();olderRequest.current=controller;try{const response=await fetch('/api/documents?id='+selected+'&before='+nextVersion,{signal:controller.signal});if(!response.ok)throw Error('Versions unavailable.');const data=await response.json();setVersions(old=>[...old,...data.versions]);setNextVersion(data.next_version);}catch(error){if((error as Error).name!=='AbortError')setNotice((error as Error).message);}finally{setBusy(false);}}
 return <main className="max-w-5xl mx-auto space-y-5"><h1 className="text-2xl font-bold">Document vault</h1><p className="text-sm text-slate-600">Confidential files, original downloads and retained version history. Access is checked on every request.</p><FileUpload kind="document" onUploaded={uploaded}/><p role="status">{notice}</p><div className="grid gap-5 md:grid-cols-2"><section className="space-y-2"><h2 className="font-semibold">Saved documents</h2><button onClick={()=>setRefresh(n=>n+1)} className="border rounded-lg p-2">Refresh</button>{!items.length&&<p className="text-sm">No documents loaded.</p>}{items.map(item=><button key={item.id} onClick={()=>{setSelected(item.id);setDocument(null);setVersions([]);setFileId('');}} className="block w-full border rounded-lg p-3 text-left" aria-pressed={selected===item.id}>{item.title}</button>)}{cursor&&<button disabled={busy} onClick={more} className="border rounded-lg p-2">Load more</button>}</section>{document&&<section className="space-y-4"><h2 className="font-semibold">{document.title}</h2><label className="block text-sm">Version<select value={fileId} onChange={e=>setFileId(e.target.value)} className="block w-full border rounded-lg p-2">{versions.map(v=><option key={v.id} value={v.id}>Version {v.version} · {v.original_name} · {Number(v.byte_size).toLocaleString()} bytes</option>)}</select></label>{nextVersion&&<button disabled={busy} onClick={older} className="border rounded-lg p-2">Load older versions</button>}{version&&<><a href={url} className="inline-block rounded-lg bg-indigo-600 px-4 py-2 text-white">Download original</a>{version.media_type==='application/pdf'?<iframe title="PDF preview" src={url+'&inline=true'} className="w-full h-96 border"/>:version.media_type==='text/plain'?<pre className="max-h-96 overflow-auto whitespace-pre-wrap text-sm border p-3">{preview}</pre>:<p>Preview unavailable for this format. Download the original file.</p>}</>}{document.can_edit&&<><form onSubmit={e=>{e.preventDefault();void mutate('rename');}} className="space-y-2"><label className="block text-sm">Document title<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} className="block w-full border rounded-lg p-2"/></label><button disabled={busy} className="border rounded-lg p-2">Save title</button></form><FileUpload key={document.id+':'+document.revision} kind="document" documentId={document.id} revision={document.revision} initialTitle={document.title} onUploaded={uploaded}/><details><summary className="text-red-700 cursor-pointer">Delete this document</summary><p className="text-sm my-2">This removes it from the vault immediately. All original versions remain in storage for 30 days.</p><button disabled={busy} onClick={()=>mutate('archive')} className="rounded-lg bg-red-700 text-white p-2">Delete document</button></details></>}</section>}</div></main>;
}
