'use client';
import { useEffect,useRef,useState } from 'react';
type Props={kind:'document'|'audio';documentId?:string;revision?:number;initialTitle?:string;onUploaded:(id:string)=>void};
export function FileUpload({kind,documentId,revision,initialTitle='',onUploaded}:Props){
 const [file,setFile]=useState<File|null>(null),[title,setTitle]=useState(initialTitle),[preacher,setPreacher]=useState(''),[day,setDay]=useState(''),[progress,setProgress]=useState(0),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');const active=useRef<XMLHttpRequest|null>(null);
 const input=useRef<HTMLInputElement|null>(null);
 useEffect(()=>()=>{active.current?.abort();},[]);
 function submit(event:React.FormEvent){event.preventDefault();if(!file)return;const maximum=(kind==='audio'?50:10)*1024*1024;if(file.size>maximum){setNotice('File exceeds the upload limit.');return;}
  const extension=file.name.split('.').at(-1)?.toLowerCase(),type=kind==='audio'?(extension==='mp3'?'audio/mpeg':extension==='wav'?'audio/wav':''):(extension==='pdf'?'application/pdf':extension==='txt'?'text/plain':'');if(!type){setNotice('Select a supported file.');return;}
  setBusy(true);setProgress(0);setNotice('');const xhr=new XMLHttpRequest();active.current=xhr;xhr.open('POST',kind==='audio'?'/api/media':'/api/documents');xhr.setRequestHeader('Content-Type',type);xhr.setRequestHeader('x-document-title',encodeURIComponent(title));xhr.setRequestHeader('x-file-name',encodeURIComponent(file.name));if(documentId){xhr.setRequestHeader('x-document-id',documentId);xhr.setRequestHeader('x-document-revision',String(revision));}if(kind==='audio'){xhr.setRequestHeader('x-preacher',encodeURIComponent(preacher));xhr.setRequestHeader('x-preached-on',day);}
  xhr.upload.onprogress=event=>{if(event.lengthComputable)setProgress(Math.round(event.loaded/event.total*100));};xhr.timeout=300000;
  xhr.onload=()=>{setBusy(false);try{const result=JSON.parse(xhr.responseText);if(xhr.status!==201)throw Error(result.error||'Upload failed.');setNotice('File saved.');setFile(null);setTitle(initialTitle);if(input.current)input.current.value='';onUploaded(result.id);}catch(error){setNotice((error as Error).message);}};
  xhr.onerror=xhr.ontimeout=()=>{setBusy(false);setNotice('Upload outcome unavailable. Refresh the list before trying again.');};xhr.onabort=()=>{setBusy(false);setNotice('Upload cancelled. Refresh the list to confirm its saved state.');};xhr.send(file);
 }
 return <form onSubmit={submit} className="space-y-3 rounded-xl border border-slate-200 bg-white p-4"><h2 className="font-semibold">{documentId?'Upload a new version':kind==='audio'?'Upload sermon audio':'Upload a document'}</h2><p className="text-sm text-slate-600">{kind==='audio'?'MP3 or PCM WAV, up to 50 MB. New sermons stay unpublished until you publish them.':'PDF or UTF-8 text, up to 10 MB. Original files are retained; documents stay confidential.'}</p>{!documentId&&<label className="block text-sm">Title<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} disabled={busy} className="block w-full border rounded-lg p-2"/></label>}{kind==='audio'&&<><label className="block text-sm">Preacher<input required maxLength={120} value={preacher} onChange={e=>setPreacher(e.target.value)} disabled={busy} className="block w-full border rounded-lg p-2"/></label><label className="block text-sm">Sermon date<input required type="date" value={day} onChange={e=>setDay(e.target.value)} disabled={busy} className="block border rounded-lg p-2"/></label></>}<label className="block text-sm">File<input ref={input} required type="file" accept={kind==='audio'?'.mp3,.wav':'.pdf,.txt'} onChange={e=>setFile(e.target.files?.[0]||null)} disabled={busy} className="block w-full p-2"/></label>{busy&&<div role="status"><progress max={100} value={progress} aria-label="Upload progress"/>{progress}% transferred{progress===100?' · Validating and saving…':''}</div>}<button disabled={busy||!file} className="rounded-lg bg-indigo-600 px-4 py-2 text-white disabled:opacity-50">Upload</button>{busy&&<button type="button" onClick={()=>active.current?.abort()} className="ml-3 border rounded-lg px-3 py-2">Cancel</button>}<p role="status" className="text-sm">{notice}</p></form>;
}
